config/routes.rb
Politreview::Application.routes.draw do
  get "omniauth_callbacks/vkontakte"
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :news do
  	resources :reviews do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
	end
  resources :politics do
    member do
      post :stars
    end
  	resources :feedbacks do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
  end
  resources :users
end

app/models/politic.rb
class Politic < ActiveRecord::Base
  belongs_to :user
  has_many :feedbacks
  has_many :votes, as: :voteable
end

app/controllers/politics_controller.rb
class PoliticsController < ApplicationController

  def new
    @politic = Politic.new
  end

  def create
    @politic = Politic.new(politic_params)
    if @politic.save
      redirect_to politic_path(@politic)
    else
      render 'new'
    end
  end

  def show 
    @politic = Politic.find(params[:id])
    @politics = Politic.all
    @feedbacks = @politic.feedbacks.order(rating: :desc)
    if @politic.votes_counter == 0.0
      @average_rate = 0.0
    else
      @average_rate = (@politic.rating / @politic.votes_counter)
    end
    if user_signed_in?
      @voted = @politic.votes.where(user_id: current_user.id).present?
    else
      @voted = true
    end
  end

  def index
    @politics = Politic.all
  end

  def edit
    @politic = Politic.find(params[:id])
  end

  def update
    @politic = Politic.find(params[:id])
    if @politic.update(politic_params)
      redirect_to @politic
    else
      render 'edit'
    end
  end

  def destroy
    @politic = Politic.find(params[:id])
    @politic.destroy
    redirect_to :root
  end

  def stars
    politic = Politic.find(params[:id])
    rate = params[:rate].to_f
    flash[:notice] = Vote.record_star(current_user, politic, rate, 'Politic', true)
    redirect_to politic
  end 

  private
  def politic_params
    params.require(:politic).permit(:name, :about, :photo_url, :post)
  end
end

app/helpers/politics_helper.rb
module PoliticsHelper
end

app/views/politics/_feedback.html.haml
- if user_signed_in?
  = form_for ([@politic, @politic.feedbacks.build]) do |f|
    %p
      = f.hidden_field :politic_id
      = f.hidden_field :user_id, :value => current_user.id
      .radio
        = f.radio_button :emo_type, "positive", id: "optionsRadios1"
        = label_tag(:optionsRadios1, "Позитивний")
      .radio
        = f.radio_button :emo_type, "neutral", id: "optionsRadios2"
        = label_tag(:optionsRadios2, "Нейтральний")
      .radio
        = f.radio_button :emo_type, "negative", id: "optionsRadios3"
        = label_tag(:optionsRadios3, "Негативний")
      = f.text_area :content, class: 'form-control', rows: 10

    %p
      = f.submit "Готово", class: 'btn btn-default'
- else
  %h2
    Режим анонімності
  - user = User.where(:username => 'Anonymous').first
  = form_for ([@politic, @politic.feedbacks.build]) do |f|
    %p
      = f.hidden_field :politic_id
      = f.hidden_field :user_id, :value => user.id
      .radio
        = f.radio_button :emo_type, "positive", id: "optionsRadios1"
        = label_tag(:optionsRadios1, "Позитивний")
      .radio
        = f.radio_button :emo_type, "neutral", id: "optionsRadios2"
        = label_tag(:optionsRadios2, "Нейтральний")
      .radio
        = f.radio_button :emo_type, "negative", id: "optionsRadios3"
        = label_tag(:optionsRadios3, "Негативний")
      = f.text_area :content, class: 'form-control', rows: 10
    %p
      = f.submit "Готово", class: 'btn btn-default'

app/views/politics/_form.html.haml
= form_for @politic do |f|
  %p
    = f.text_field :photo_url, placeholder: "Посилання на картинку"
  %p
    = f.text_field :name, placeholder: "ФІО пацієнта"
  %p
    = f.text_field :post, placeholder: "Назва хвороби(посада)"
  %p
    = f.text_area :about, placeholder: "Історія хвороби"
  %p
    = f.submit 'Створити!'

app/views/politics/edit.html.haml
= render 'politics/form'

app/views/politics/index.html.haml
= content_for(:title, "Усі політики | politreview.com")
- @politics.each do |politic|
  .hot-politics.col-md-2.col-xs-4
    = link_to(image_tag(politic.photo_url, class: 'resize'), politic_path(politic))
    %h5.name
      = politic.name
    .feedbacks-rating
      %h6.feedbacks 43 
      %h6.rating 12%

app/views/politics/show.html.haml
= content_for(:title, "#{@politic.name}. Відгуки | politreview.com")
- if user_signed_in?
  - if current_user.admin?
    = link_to 'Коригувати', edit_politic_path(@politic)
    = link_to 'В пічку!', politic_path(@politic), method: :delete
.row
  .col-md-4.col-xs-4
    .photo
      .object
        .frame
          .canvas
            = image_tag(@politic.photo_url)
  .col-md-8.col-xs-12
    .politic-name
      = @politic.name 
    %h3
      Діагноз:
      = @politic.post
    - if @voted
      %span.star-rating-dis
        - (1...11).each do |i|
          - if i <= @average_rate
            %span.star-gold
          - else
            %span.star-grey
    -else
      %span.star-rating.active
        %span.star{ data: { :politic_id => @politic.id, :rate => 10} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 9} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 8} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 7} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 6} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 5} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 4} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 3} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 2} }
        %span.star{ data: { :politic_id => @politic.id, :rate => 1} }
    %span.average-rating  
      = "#{@average_rate}/10"
    .votes_counter
      = "Людей проголосувало: #{@politic.votes.count}"
.row
  .about-politic.col-md-12.col-xs-12
    %h4
      Історія хвороби: 
      = @politic.about
- @feedbacks.each do |feedback|
  %div{class: feedback.emo_type}
    %a{name: feedback.id}
    .feedback
      .feedback-header
        .user
          .username
            = feedback.user.username
          - if request.location.country == 'Ukraine'
            .flag.flag-ua
          - elsif request.location.country == 'Russia'
            .flag.flag-ru
          - elsif request.location.country == 'Reserved'
            .flag.flag-eu
          - else
            %span
              = request.location.country
          - if user_signed_in?
            - if current_user.admin?
              = link_to 'В пічку!', politic_feedback_path(@politic, feedback), method: :delete
        .date
          %h4
            = feedback.created_at.to_s(:ru_datetime)
      .feedback-content
        = feedback.content
      .feedback-footer
        .links
          .feedback-link
            = link_to 'Посилання на відгук', politic_path(@politic, anchor: feedback.id)
          .comment-link
            = link_to "Обговорення (#{feedback.comments.count})", politic_feedback_path(@politic, feedback)
        - if user_signed_in?
          - if feedback.user.id == current_user.id
            .voted
              .rating
                = feedback.rating
          - else
            - if current_user.voted_for?(feedback.id)
              - if current_user.positive_vote?(feedback.id)
                .voted
                  .rating
                    = feedback.rating
                  %i.voted-for.fa.fa-thumbs-up.green
              - else 
                .voted
                  .rating
                    = feedback.rating
                  %i.voted-against.fa.fa-thumbs-down.red
            - else
              .votes.make-vote
                .rating
                  = feedback.rating
                %i.vote-for.fa.fa-thumbs-o-up{ data: {:article_type => "/politics/", :article_id => @politic.id, :voteable_type => "/feedbacks/", :voteable_id => feedback.id} }
                %i.vote-against.fa.fa-thumbs-o-down{ data: {:article_type => "/politics/", :article_id => @politic.id, :voteable_type => "/feedbacks/", :voteable_id => feedback.id} }
        - else
          .votes
            = link_to '', new_user_session_path, class: 'vote-for fa fa-thumbs-o-up'
            = link_to '', new_user_session_path, class: 'vote-against fa fa-thumbs-o-down'
            .rating
              = feedback.rating
%h1
  Залишити відгук
= render 'feedback'