config/routes.rb
Politreview::Application.routes.draw do
  get "omniauth_callbacks/vkontakte"
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :news do
  	resources :reviews do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
	end
  resources :politics do
    member do
      post :stars
    end
  	resources :feedbacks do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
  end
  resources :users
end

app/models/news.rb
class News < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to news_path(@news)
    else
      render 'new'
    end
  end

  def show
    @news = News.find_by_id(params[:id])
    @reviews = @news.reviews.order('rating DESC')
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to @news
    else
      render 'edit'
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to :root
  end

  private
  def news_params
    params.require(:news).permit(:title, :content, :user_id)
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.haml
= form_for @news do |f|
  %p
    = f.hidden_field :user_id, :value => current_user.id
    %br
    = f.text_field :title, class: 'form-control', placeholder: "Заголовок"

  %p
    = f.text_area :content, class: 'form-control ckeditor', rows: 10

  %p
    = f.submit "Готово", class: 'btn btn-default'

app/views/news/_review.html.haml
- if user_signed_in?
  = form_for ([@news, @news.reviews.build]) do |f|
    %p
      = f.hidden_field :news_id
      = f.hidden_field :user_id, :value => current_user.id
      .radio
        = f.radio_button :emo_type, "positive", id: "optionsRadios1"
        = label_tag(:optionsRadios1, "Позитивна")
      .radio
        = f.radio_button :emo_type, "neutral", id: "optionsRadios2"
        = label_tag(:optionsRadios2, "Нейтральна")
      .radio
        = f.radio_button :emo_type, "negative", id: "optionsRadios3"
        = label_tag(:optionsRadios3, "Негативна")
      = f.text_area :content, class: 'form-control', rows: 10

    %p
      = f.submit "Готово", class: 'btn btn-default'
- else
  %h2
    Режим анонімності
  = form_for ([@news, @news.reviews.build]) do |f|
    - @user = User.where(username: 'Anonymous').first
    %p
      = f.hidden_field :news_id
      = f.hidden_field :user_id, :value => @user.id
      .radio
        = f.radio_button :emo_type, "positive", id: "optionsRadios1"
        = label_tag(:optionsRadios1, "Позитивна")
      .radio
        = f.radio_button :emo_type, "neutral", id: "optionsRadios2"
        = label_tag(:optionsRadios2, "Нейтральна")
      .radio
        = f.radio_button :emo_type, "negative", id: "optionsRadios3"
        = label_tag(:optionsRadios3, "Негативна")
      = f.text_area :content, class: 'form-control', rows: 10

    %p
      = f.submit "Готово", class: 'btn btn-default'

app/views/news/edit.html.haml
= render 'news/form'

app/views/news/new.html.haml
- if user_signed_in?
  - if current_user.admin?
    = render 'form'
- else
  %h1
    У вас недостатньо прав добавлення новин.

app/views/news/show.html.haml
= content_for(:title, "#{@news.title}. Рецензії | politreview.com")
- if user_signed_in?
  - if current_user.admin?
    = link_to 'Коригувати', edit_news_path(@news)
    = link_to 'В пічку!', news_path(@news), method: :delete
%h1  
  = @news.title
= raw @news.content
- @reviews.each do |review|
  %div{class: review.emo_type}
    %a{name: review.id}
    .review
      .review-header
        .user
          .username
            = review.user.username
          - if request.location.country == 'Ukraine'
            .flag.flag-ua
          - elsif request.location.country == 'Russia'
            .flag.flag-ru
          - elsif request.location.country == 'Reserved'
            .flag.flag-eu
          - else
            %span
              = request.location.country
          - if user_signed_in?
            - if current_user.admin?
              = link_to 'В пічку!', news_review_path(@news, review), method: :delete
        .date
          %h4
            = review.created_at.to_s(:ru_datetime)
      .review-content
        = review.content
      .review-footer
        .links
          .review-link
            = link_to 'Посилання на рецензію', news_path(@news, anchor: review.id)
          .comment-link
            = link_to "Обговорення (#{review.comments.count})", news_review_path(@news, review)
        - if user_signed_in?
          - if review.user.id == current_user.id
            .voted
              .rating
                = review.rating
          - else
            - if current_user.voted_for?(review.id)
              - if current_user.positive_vote?(review.id)
                .voted
                  .rating
                    = review.rating
                  %i.voted-for.fa.fa-thumbs-up.green
              - else 
                .voted
                  .rating
                    = review.rating
                  %i.voted-against.fa.fa-thumbs-down.red
            - else
              .votes.make-vote
                .rating
                  = review.rating
                %i.vote-for.fa.fa-thumbs-o-up{ data: {:article_type => "/news/", :article_id => @news.id, :voteable_type => "/reviews/", :voteable_id => review.id} }
                %i.vote-against.fa.fa-thumbs-o-down{ data: {:article_type => "/news/", :article_id => @news.id, :voteable_type => "/reviews/", :voteable_id => review.id} }
        - else
          .votes
            = link_to '', new_user_session_path, class: 'vote-for fa fa-thumbs-o-up'
            = link_to '', new_user_session_path, class: 'vote-against fa fa-thumbs-o-down'
            .rating
              = review.rating
%h1
  Написати рецензію
= render 'review'