config/routes.rb
Politreview::Application.routes.draw do
  get "omniauth_callbacks/vkontakte"
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :news do
  	resources :reviews do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
	end
  resources :politics do
    member do
      post :stars
    end
  	resources :feedbacks do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
  end
  resources :users
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @news = News.find_by_id(params[:news_id])
    if @review.save
      redirect_to news_path(@news)
    else
      render 'new'
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
    #@comment_review = Review.find_by_id(params[:review_id])
    @news = News.find_by_id(params[:news_id])
    @remote_ip = request.env["HTTP_X_FORWARDED_FOR"]
    #@country = GeoIP.new('lib/GeoIP.dat').country(request.remote_ip) 
    @comment = Comment.new
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to :back
  end

  def vote_up
    @review = Review.find(params[:id])
    @news = News.find(params[:news_id])
    Vote.record_vote(current_user, @review, 1, 'Review', true)
    redirect_to :back
  end

  def vote_down
    @review = Review.find(params[:id])
    @news = News.find(params[:news_id])
    Vote.record_vote(current_user, @review, -1, 'Review', false)
    redirect_to :back
  end

  private
  def review_params
    params.require(:review).permit(:content, :user_id, :emo_type, :news_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_comment.html.haml
- if user_signed_in?
  = form_for ([@news, @review, @comment]) do |f|
    %p
      = f.hidden_field :commentable_id, :value => @review.id
      = f.hidden_field :user_id, :value => current_user.id
      = f.hidden_field :commentable_type, :value => 'Review'
      = f.text_area :content, class: 'form-control', rows: 10

    %p
      = f.submit "Готово", class: 'btn btn-default'
- else
  %h2
    Режим анонімності
  = form_for ([@news, @review, @comment]) do |f|
    - user = User.where(:username => 'Anonymous').first
    %p
      = f.hidden_field :commentable_id, :value => @review.id
      = f.hidden_field :user_id, :value => user.id
      = f.hidden_field :commentable_type, :value => 'Review'
      = f.text_area :content, class: 'form-control', rows: 10

    %p
      = f.submit "Готово", class: 'btn btn-default'

app/views/reviews/show.html.haml
= content_for(:title, "Рецензія №#{@review.id} | politreview.com")
%h1
  Рецензія № 
  = @review.id
  на новость
  = link_to @news.title, news_path(@news)
= @review.content
.comments
  %h3
    Коментарі:
  - @review.comments.each do |comment|
    .feedback
      .feedback-header
        .user
          .username
            = comment.user.username
          - if request.location.country == 'Ukraine'
            .flag.flag-ua
          - elsif request.location.country == 'Russia'
            .flag.flag-ru
          - elsif request.location.country == 'Reserved'
            .flag.flag-eu
          - else
            %span
              = request.location.country
          - if user_signed_in?
            - if current_user.admin?
              = link_to 'В пічку!', news_review_comment_path(@news, @review, comment), method: :delete
        .date
          %h4
            = comment.created_at.to_s(:ru_datetime)
      .feedback-content
        = comment.content
= render 'comment'