config/routes.rb
Politreview::Application.routes.draw do
  get "omniauth_callbacks/vkontakte"
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :news do
  	resources :reviews do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
	end
  resources :politics do
    member do
      post :stars
    end
  	resources :feedbacks do
      member do
        post :vote_up
        post :vote_down
      end
  		resources :comments
  	end
  end
  resources :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter, polymorphic: true
  belongs_to :user
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	before_destroy :clear_comments, dependent: :destroy

	has_many :votes, as: :voteable
	has_many :comments, as: :commentable
	belongs_to :user
	belongs_to :politic

	protected
	def clear_comments
		comments.clear
	end
end

app/models/news.rb
class News < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
end

app/models/politic.rb
class Politic < ActiveRecord::Base
  belongs_to :user
  has_many :feedbacks
  has_many :votes, as: :voteable
end

app/models/review.rb
class Review < ActiveRecord::Base
  before_destroy :clear_comments, dependent: :destroy

  has_many :comments, as: :commentable
  belongs_to :user
  belongs_to :news
  has_many :votes, as: :voteable

  protected
	def clear_comments
		comments.clear
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :news
  has_many :politics
  has_many :reviews
  has_many :feedbacks
  has_many :comments
  has_many :votes
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+\Z/
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false, message: "занато" },
                      length: { minimum: 3, maximum: 15, message: "должно быть в пределе 3-15 символов" }

  def self.find_for_vkontakte_oauth access_token
    if user = User.where(url: access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(provider: access_token.provider, url: access_token.info.urls.Vkontakte, avatar_url: access_token.info.image, username: access_token.info.name, email: access_token.extra.raw_info.screen_name + '@vk.com', password: Devise.friendly_token[0,20]) 
    end
  end

  def voted_for?(voteable)
    votes.where(voteable_id: voteable).first.present?
  end

  def positive_vote?(voteable)
    votes.where(voteable_id: voteable).first.rate >= 1
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :voteable, polymorphic: true

	def self.record_star(user, voteable, rate, voteable_type, good_vote)
		new_vote = Vote.new
		new_vote.user_id = user.id
		new_vote.voteable_id = voteable.id
		new_vote.voteable_type = voteable_type
		new_vote.rate = rate
		new_vote.good_vote = good_vote
		voteable.rating += rate
		voteable.votes_counter += 1.0
		if new_vote.rate >= 1.0 && new_vote.rate <= 10.0
			if new_vote.save
				voteable.save
				"Ваш голос враховано"
			else
				"Ви вже голосували"
			end
			"Помилка"
		end
	end

	def self.record_vote(user, voteable, rate, voteable_type, good_vote)
		new_vote = Vote.new
		new_vote.user_id = user.id
		new_vote.voteable_id = voteable.id
		new_vote.voteable_type = voteable_type
		new_vote.rate = rate
		new_vote.good_vote = good_vote
		voteable.rating += rate
		if new_vote.save
			voteable.save
		end
	end
	
	validates :user_id,
  			uniqueness: { scope: :voteable_id, message: "Ви вже голосували" }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@politics = Politic.all.limit(6).order(votes_counter: :desc)
  	@news = News.last
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to news_path(@news)
    else
      render 'new'
    end
  end

  def show
    @news = News.find_by_id(params[:id])
    @reviews = @news.reviews.order('rating DESC')
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to @news
    else
      render 'edit'
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to :root
  end

  private
  def news_params
    params.require(:news).permit(:title, :content, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @news = News.find_by_id(params[:news_id])
    if @review.save
      redirect_to news_path(@news)
    else
      render 'new'
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
    #@comment_review = Review.find_by_id(params[:review_id])
    @news = News.find_by_id(params[:news_id])
    @remote_ip = request.env["HTTP_X_FORWARDED_FOR"]
    #@country = GeoIP.new('lib/GeoIP.dat').country(request.remote_ip) 
    @comment = Comment.new
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to :back
  end

  def vote_up
    @review = Review.find(params[:id])
    @news = News.find(params[:news_id])
    Vote.record_vote(current_user, @review, 1, 'Review', true)
    redirect_to :back
  end

  def vote_down
    @review = Review.find(params[:id])
    @news = News.find(params[:news_id])
    Vote.record_vote(current_user, @review, -1, 'Review', false)
    redirect_to :back
  end

  private
  def review_params
    params.require(:review).permit(:content, :user_id, :emo_type, :news_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @reviews_feedbacks = @user.reviews.all + @user.feedbacks.all
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def on_the_edit_page?
		controller_name == 'news' && action_name == 'new' || action_name == 'edit'
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/politics_helper.rb
module PoliticsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer
  %hr
  .cr
    PolitReview 2014

app/views/layouts/_header.html.haml
%header
  .logo
    .brand
      =link_to 'PolitReview.com', root_path
    .user-nav
      - if user_signed_in?
        %ul
          %h4
            %li= link_to current_user.username, user_path(current_user), title: "Профіль"
            %li= link_to ' Вихід', destroy_user_session_path, method: :delete, class: "fa fa-sign-out", title: "Вихід"
      - else
        %ul
          %h4
            %li= link_to 'Ввійти', new_user_session_path
            %li= link_to 'Зареєстуватись', new_user_registration_path
            %li= link_to(image_tag('http://wiki.qip.ru/public/f/f6/%D0%98%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0_vkontakte.png'), user_omniauth_authorize_path(:vkontakte))   
  %nav.navigation
    - if user_signed_in?
      - if current_user.admin?
        = link_to 'Додати політика', new_politic_path
        = link_to 'Додати новину', new_news_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title)
    = stylesheet_link_tag "application", media: "all"
    - if on_the_edit_page?
      = javascript_include_tag "editor"
    - else
      = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1", name: "viewport", "user-scalable" => "no"}/
  %body.col-md-offset-2.col-sm-offset-2.col-xs-12.col-sm-8.col-md-8
    = render 'layouts/header'
    .row
      .hot-news.col-md-8.col-xs-12
        = yield
      .sidebar.col-md-4.col-xs-12
        .politics
          %h2 
            = link_to 'Політики', politics_path
          - @politics.each do |politic|
            .hot-politic.col-md-4.col-xs-4
              = link_to(image_tag(politic.photo_url, class: 'resize'), politic_path(politic))
        .recent-news
          %h2 Більше
          - @recent_news.each do |news|
            .single-recent-news
              .date-counter
                .created-at
                  = news.created_at.to_s(:ru_datetime)
                .reviews-counter.fa.fa-comments-o
                  = news.reviews.count
              = link_to news.title, news_path(news)
            %hr
    = render 'layouts/footer'

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title PolitReview.com - оцінка політиків, їх діяльності, а також останніх подій в Україні
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1", name: "viewport", "user-scalable" => "no"}/
    %meta{content: "politreview.com - це сайт, на якому можна залишати відгуки про політиків та рецензії на найгостріщі новини України", name: "description"}/
    %meta{content: "Євромайдан, політика, політична ситуація, президент України, політична критика, відгуки про політиків", name: "keywords"}/
  %body.col-md-offset-2.col-sm-offset-2.col-xs-12.col-sm-8.col-md-8 
    = render 'layouts/header'
    
    %h2 
      = link_to 'Політики', politics_path
    .row
      - @politics.each do |politic|
        .hot-politics.col-md-2.col-xs-4
          = link_to(image_tag(politic.photo_url, class: 'resize'), politic_path(politic))
          .politic-rating
            %h6.feedbacks.fa.fa-comments-o
              = politic.feedbacks.count
            %h6.rating
              - if politic.votes_counter == 0.0
                - average_rate = 0.0
              - else
                - average_rate = (politic.rating / politic.votes_counter)
              %span
                = average_rate
                = "/10"       
    .row
      .hot-news.col-md-8.col-xs-12
        .hot-news-header
          .title
            = link_to @news.title, news_path(@news)
        .news-content
          = raw @news.content
      .recent-news.col-md-4.col-xs-12
        %h2 Більше
        - @recent_news.each do |news|
          .single-recent-news
            .date-counter
              .created-at
                = news.created_at.to_s(:ru_datetime)
              .reviews-counter.fa.fa-comments-o
                = news.reviews.count
            = link_to news.title, news_path(news)
          %hr
    = render 'layouts/footer'